### ISSUE TITLE
About routing tables

### ISSUE THREAD

**Issue by tohoanglinh** [mikelizal/OBSmodules#1]
In treetopologyOBS, core*route.dat, can you explain:

Core2route.dat:
0 \* 2 0 \* 2
1 \* 2 0 \* 2
0 \* \* 1 \* *
#1 \* \* 1 \* \* (Why we remove this line?, should it mean all bursts from input port go to output port 1...?)

Core3route.dat
0 \* 3 0 \* 3
....

So what will happen if bursts with label 2 go to core 3

For a big topology like NSFNet
![nsfnet](https://f.cloud.github.com/assets/2783659/67763/83901f86-5f17-11e2-84a8-1c6682d6303b.jpg), what type of routing table parameters should I add ?

**Comment by felixespina** [comment]
Each line of the routing file has the following format:

InputFiber InputWavelength InputLabel OutputFiber OutputWavelength OutputLabel

First, you have to identify each fiber of each core node. They are numbered (starting at 0) as they are added to the core node in the network topology (the NED file). For example, for the Core2 the first fiber is the fiber between Core2 and Edge2 and the second fiber is the fiber between Core2 and Core1.

Normally, you want all traffic coming from the Edge2 to be forwarded to Core1, regardless of the wavelength and label:
0 \* \* 1 \* *
Traffic directed to Edge2 should not come from Edge2, but for safety, you can add an extra route for this traffic. This traffic is identified with the label 2 in this example:
0 \* 2 0 \* 2
Only traffic directed to Edge2 should arrive from Core1. This traffic is identified with the label 2 in this example:
1 \* 2 0 \* 2
Traffic not directed to Edge2 should not arrive to Core2 from Core1, but for safety, if you want to redirect this type of traffic to Core1, you can add this route at the beginning of the routing file:
1 \* \* 1 \* *
If you want to add this line, you must add to the beginning of the file, because the routing module execute the last entry in the file that meets the burst parameters. So, if you add the line to the end of the file, all burst arriving from fiber 1 will be redirected to fiber 1, regardless the destination would be Edge2.

Therefore, the Core2route.dat should be:
0 \* \* 1 \* *
0 \* 2 0 \* 2
1 \* 2 0 \* 2

or

0 \* \* 1 \* *
1 \* \* 1 \* *
0 \* 2 0 \* 2
1 \* 2 0 \* 2

Using these procedure you can configure the route files of the NSFNet. The easiest way is to set a label to each edge node, choose the routes between nodes and fill the routing files that enable these routing paths.

**Comment by tohoanglinh** [comment]
Dear mr. Felix Espina.

Really thank you so much.......

You have helped me so much. I can make other topologies working well, too.

My next difficulty is:  I am trying to monitor statistics of OBS.

one of important issues I think is the dropped burst number or blocking
probability. I am trying to monitor it at Core node (with scalar you added
already).

Do you have any idea of monitor burst blocking probability in OBS ( core,
edge, or standard host). Also the end.to.end delay of  burst, I want to
modify it through modify standard host, but I don't know which module
should I adjust.

Sent from my iPad 4th generation

On 2013. 1. 23., at 오전 12:05, Felix Espina notifications@github.com wrote:

Each line of the routing file has the following format:

InputFiber InputWavelength InputLabel OutputFiber OutputWavelength
OutputLabel

First, you have to identify each fiber of each core node. They are numbered
(starting at 0) as they are added to the core node in the network topology
(the NED file). For example, for the Core2 the first fiber is the fiber
between Core2 and Edge2 and the second fiber is the fiber between Core2 and
Core1.

Normally, you want all traffic coming from the Edge2 to be forwarded to
Core1, regardless of the wavelength and label:
0 \* \* 1 \* *
Traffic directed to Edge2 should not come from Edge2, but for safety, you
can add an extra route for this traffic. This traffic is identified with
the label 2 in this example:
0 \* 2 0 \* 2
Only traffic directed to Edge2 should arrive from Core1. This traffic is
identified with the label 2 in this example:
1 \* 2 0 \* 2
Traffic not directed to Edge2 should not arrive to Core2 from Core1, but
for safety, if you want to redirect this type of traffic to Core1, you can
add this route at the beginning of the routing file:
1 \* \* 1 \* *
If you want to add this line, you must add to the beginning of the file,
because the routing module execute the last entry in the file that meets
the burst parameters. So, if you add the line to the end of the file, all
burst arriving from fiber 1 will be redirected to fiber 1, regardless the
destination would be Edge2.

Therefore, the Core2route.dat should be:
0 \* \* 1 \* *
0 \* 2 0 \* 2
1 \* 2 0 \* 2

or

0 \* \* 1 \* *
1 \* \* 1 \* *
0 \* 2 0 \* 2
1 \* 2 0 \* 2

Using these procedure you can configure the route files of the NSFNet. The
easiest way is to set a label to each edge node, choose the routes between
nodes and fill the routing files that enable these routing paths.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mikelizal/OBSmodules/issues/1#issuecomment-12548277.

**Comment by felixespina** [comment]
OBSmodules has some scalars that can help you.

At the end of the simulation each Edge Node outputs to the .sca file the number of burst sent, the number of burst dropped by reaching Minimum Offset and the number of burst dropped by queue. The total number of burst of the edge node is the sum of the three numbers. These numbers look at the .sca file like:

scalar jitel09Simulation.edge2.obs.assembler.sender     "burst sent"    6252
scalar jitel09Simulation.edge2.obs.assembler.sender     "burst dropped by reaching Minimum Offset"  0
scalar jitel09Simulation.edge2.obs.assembler.sender     "burst dropped by queue"    0

Each Core Node outputs the number of Burst dropped in Core Node. It looks like:

scalar jitel09Simulation.core1.ControlUnit.ControlLogic     "Burst dropped in Core Node"    0

Currently OBSModules does not measure the end to end delay of bursts. You cannot measure the end to end delay of bursts modifying the Standard Host, but you can measure the end to end delay of packets. You should modify the disassembler module to measure  the end to end delay of bursts.
